[build-system]
requires = ["setuptools>=69.0.3", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[project]
name = "python_template_repository"
authors = [{ name = "Flyability", email = "sws@flyability.com" }]
description = "<ADD PACKAGE DESCRIPTION>"
license = { text = "FlyaPrivate" }
requires-python = ">=3.11"
dynamic = ["version"]
readme = "README.md"

dependencies = []

[project.optional-dependencies]
test = ["pytest", "pytest-cov"]
doc = [
    "docutils",
    "myst-parser>=2.0.0",
    "sphinx>=7.0.0",
    "sphinx-autodoc-typehints",
    "sphinx-copybutton",
    "sphinx-rtd-theme>=2.0.0",
    "sphinxcontrib-programoutput",
]
lint = [
    "black",
    "ruff",
    "mypy",
    "pydoclint",
    "pytest",    # required for mypy
]
dev = ["python_template_repository[test,doc,lint]"]

[project.scripts]

######### TOOLS #########
[tool.black]
target-version = ["py311", "py312"]
line-length = 90


[tool.ruff]
line-length = 90
extend-exclude = ["docs/"]
fix = true

[tool.ruff.lint]
fixable = ["I"]
ignore = [
    "E501", # black compatibility
    "E203", # black compatibility
]
select = [
    "F",   # pyflakes
    "E",   # pycodestyle
    "W",   # pycodestyle
    "I",   # isort
    "N",   # pep8-naming
    "C90", # mccabe complexity

    # Additional checks from ruff
    "G",      # logging
    "PTH",    # use pathlib
    "PIE",    # flake8-pie
    "TCH",    # type checking imports
    "TID252", # relative imports
]

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["python_template_repository"]

[tool.ruff.lint.mccabe]
max-complexity = 10


[tool.mypy]
# Logistics of what code to check and how to handle the data.
scripts_are_modules = true
show_traceback = true

# Options to make the checking stricter.
check_untyped_defs = true
disallow_untyped_defs = true
disallow_any_generics = true
warn_no_return = true
strict_optional = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true

# Display the codes needed for # type: ignore[code] annotations.
show_error_codes = true

# Warn of unreachable or redundant code.
warn_unreachable = true

exclude = ["docs/", ".venv/", "build/"]

# We use some third-party libraries we don't have stubs for. Ignore them.
[[tool.mypy.overrides]]
module = ["some_module"]
ignore_missing_imports = true


[tool.pytest.ini_options]
junit_family = "xunit2"
addopts = ["--import-mode=importlib"]

[tool.coverage.run]
source = ["src"]
source_pkgs = ["python_template_repository"]
relative_files = true

[tool.coverage.paths]
source = [
    "src/python_template_repository",
    "*/site-packages/python_template_repository",
]


[tool.pydoclint]
style = 'sphinx'
exclude = "docs/|.venv/|build/"
arg_type_hints_in_docstring = false
check_return_types = false
check_yield_types = false
allow_init_docstring = true
skip_checking_raises = true
