sonar.projectKey=Flyability_python-template-repository
sonar.organization=flyability-github

sonar.sources=src
sonar.exclusions=build/*

sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=xunit-result.xml
sonar.exclusions=build/*
sonar.python.version=3.12