from abc import ABC, abstractmethod

import numpy as np
from numpy import float32
from numpy.typing import NDArray


class Thrusters(ABC):
    @abstractmethod
    def set_target_rotor_speeds(self, rotor_speeds: NDArray[float32]) -> None:
        pass

    @abstractmethod
    def update(self, dt: float) -> NDArray[float32]:
        """
        Method that updates the thrusters and returns the thrusts generated by the
        thrusters.

        Args:
            dt (float): The time elapsed between the previous and current function calls
            (s).

        Returns:
            A list with the thrusts generated by each individual thruster.
        """

    @abstractmethod
    def thrusts_from_rotor_speeds(
        self, rotor_speeds: NDArray[float32]
    ) -> NDArray[float32]:
        pass

    @abstractmethod
    def rotor_speeds_from_thrusts(self, thrusts: NDArray[float32]) -> NDArray[float32]:
        pass


class Elios3Thrusters(Thrusters):
    def __init__(self, num_rotors: int) -> None:
        super().__init__()

        self.num_rotors = num_rotors

        self.max_rotor_velocity = 20e3
        self.min_rotor_velocity = -20e3

        self.target_rotor_speeds = np.zeros(self.num_rotors, dtype=float32)

        self.square_coeff_pos_th = 3.747094e-8
        self.lin_coeff_pos_th = -3.311279e-5

        self.square_coeff_neg_th = -1.417321e-8
        self.lin_coeff_neg_th = 2.952006e-6

    def set_target_rotor_speeds(self, rotor_speeds: NDArray[float32]) -> None:
        self.target_rotor_speeds = rotor_speeds

    def update(self, dt: float) -> NDArray[float32]:
        rotor_speeds = np.clip(
            self.target_rotor_speeds, self.min_rotor_velocity, self.max_rotor_velocity
        )
        return self.thrusts_from_rotor_speeds(rotor_speeds)

    def rotor_speeds_from_thrusts(self, thrusts: NDArray[float32]) -> NDArray[float32]:
        rotor_speeds = np.zeros(self.num_rotors, dtype=float32)
        for i in range(self.num_rotors):
            rotor_speeds[i] = self.rotor_speed_from_thrust(thrusts[i])

        return rotor_speeds

    def thrusts_from_rotor_speeds(
        self, rotor_speeds: NDArray[float32]
    ) -> NDArray[float32]:
        thrusts = np.zeros(self.num_rotors, dtype=float32)
        for i in range(self.num_rotors):
            thrusts[i] = self.thrust_from_rotor_speed(rotor_speeds[i])

        return thrusts

    def rotor_speed_from_thrust(self, thrust: float) -> float:
        if thrust > 0.0:
            return (
                np.sqrt(4 * self.square_coeff_pos_th * thrust + self.lin_coeff_pos_th**2)
                - self.lin_coeff_pos_th
            ) / (2 * self.square_coeff_pos_th)
        else:
            return (
                np.sqrt(4 * self.square_coeff_neg_th * thrust + self.lin_coeff_neg_th**2)
                - self.lin_coeff_neg_th
            ) / (2 * self.square_coeff_neg_th)

    def thrust_from_rotor_speed(self, rotor_speed: float) -> float:
        if rotor_speed > 0.0:
            return (
                self.square_coeff_pos_th * rotor_speed**2
                + self.lin_coeff_pos_th * rotor_speed
            )
        else:
            return (
                self.square_coeff_neg_th * rotor_speed**2
                + self.lin_coeff_neg_th * rotor_speed
            )
