name: Release package
on:
  push:
    branches:
      - 'master'
    tags:
      - '**'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-windows-binary:
    name: Build executable on Windows
    runs-on: [windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.FLYABOT_PAT }}
          submodules: recursive
      - name: Setup python
        id: setup-python
        uses: Flyability/setup-python-package@1.0.0
        with:
          artifactory-user: ${{ secrets.ARTIFACTORY_USER }}
          artifactory-password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          pip-install: ". pyinstaller"
          python-version: 3.12
      - name: Generate exe with PyInstaller
        run: |
          pyinstaller --onefile --name ${{ steps.setup-python.outputs.package-name }}_${{ steps.setup-python.outputs.package-version }} src/python_template_repository/scripts/dummy.py
      - name: Upload executable to github
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.setup-python.outputs.package-name }}_${{ steps.setup-python.outputs.package-version }}
          path: |
            dist/*.exe
      - name: Upload to JFrog Artifactory
        if: startsWith(github.ref, 'refs/tags')
        uses: jfrog/setup-jfrog-cli@v4
      - name: Upload to JFrog
        if: startsWith(github.ref, 'refs/tags')
        run: |
            jfrog config add flya --artifactory-url=${{ secrets.ARTIFACTORY_URL }} --user=${{ secrets.ARTIFACTORY_USER }} --password=${{ secrets.ARTIFACTORY_PASSWORD }}
            cd dist
            jfrog rt upload *.exe "generic-local/tools/gaston/${{ steps.setup-python.outputs.package-name }}/"